# Use the specific version of Golang
FROM golang:1.21.5

# Set the working directory in the container
WORKDIR /app

# Copy the Go Modules manifests and other necessary files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the rest of the source code
COPY . .

# Build argument for setting the mode (with a default value)
ARG MODE=DEV

# Build the application
RUN go build -o main -tags ${MODE} -ldflags "-X main.Mode=${MODE}" ./cmd/api

# This container exposes port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./main"]